#!/usr/bin/env bash
# This script installs nginx on a server
apt-get update
apt install -y nginx

echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root var/www/html;
	index index.html index.htm index.nginx-debian.html
}
" > /etc/nginx/sites-available/default

service nginx restart
