#!/usr/bin/env bash
# This script installs nginx on a server
echo "Updating the cache"
sudo apt-update
echo "Installing Nginx
sudo apt install nginx
sudo echo "Hello world!" > /var/www/html/index.nginx-debian.html
