#!/usr/bin/env bash
# Installs Nginx with the following configurations:
apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

mkdir -p /var/www/html

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_page.html
echo "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /var/www/html;
	index       index.html index.htm;

	location / {
		try_files $uri $uri/ =404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
	}

	error_page 404 /error_page.html;
	location = /error_page.html {
		internal;
	}
}
" > /etc/nginx/sites-available/default

service nginx restart
