#!/usr/bin/env bash
# Installs Nginx with the following configurations:
apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

mkdir -p /var/www/html

hostname=$(hostname)

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /var/www/html;
	index       index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
	add_header X-Served-By $hostname;
}
" > /etc/nginx/sites-available/default

service nginx restart
