#!/usr/bin/env bash
# Configuring nginx in the server
apt-get update
apt-get install -y nginx
systemctl start nginx
systemctl enable nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;
	
	server_name _;

	add_header X-Served-By \$hostname;
	
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;

	location = /404.html {
		internal;
	}
}" > /etc/nginx/sites-available/default	

service nginx restart
