#!/usr/bin/env bash
#this script uses while loop to print "Best School" 10 times but at the 9th hi

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
