#!/usr/bin/env bash
#This script displays the content of the current directory
#In list format
#Where only the part of the name after the dash is displayed

for file in *
do
	echo "$file" | cut -d '-' -f 2-
done
