#!/usr/bin/env bash
#This script configures an ubuntu server with the following requirements

cp /etc/hosts ~/hosts.new

echo "localhost        127.0.0.2" >> ~/hosts.new
echo "facebook.com        8.8.8.8" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
